if(!require("pacman"))install.packages("pacman")
pacman::p_load("fs", "readr", "feather")

#----download----
dir_create("data", "raw")
temp <- tempfile()
download.file("http://openpsychometrics.org/_rawdata/MACH_data.zip", temp)
# alternative source:
# https://github.com/aaronpeikert/StuSti-KI-Hackathon-Alpha/releases/download/data-v1.0/MACH_data.zip
unzip(temp, exdir = path("data", "raw"))

#----read----
mach_spec <- cols(
  Q1A = col_integer(),
  Q1I = col_integer(),
  Q1E = col_integer(),
  Q2A = col_integer(),
  Q2I = col_integer(),
  Q2E = col_integer(),
  Q3A = col_integer(),
  Q3I = col_integer(),
  Q3E = col_integer(),
  Q4A = col_integer(),
  Q4I = col_integer(),
  Q4E = col_integer(),
  Q5A = col_integer(),
  Q5I = col_integer(),
  Q5E = col_integer(),
  Q6A = col_integer(),
  Q6I = col_integer(),
  Q6E = col_integer(),
  Q7A = col_integer(),
  Q7I = col_integer(),
  Q7E = col_integer(),
  Q8A = col_integer(),
  Q8I = col_integer(),
  Q8E = col_integer(),
  Q9A = col_integer(),
  Q9I = col_integer(),
  Q9E = col_integer(),
  Q10A = col_integer(),
  Q10I = col_integer(),
  Q10E = col_integer(),
  Q11A = col_integer(),
  Q11I = col_integer(),
  Q11E = col_integer(),
  Q12A = col_integer(),
  Q12I = col_integer(),
  Q12E = col_integer(),
  Q13A = col_integer(),
  Q13I = col_integer(),
  Q13E = col_integer(),
  Q14A = col_integer(),
  Q14I = col_integer(),
  Q14E = col_integer(),
  Q15A = col_integer(),
  Q15I = col_integer(),
  Q15E = col_integer(),
  Q16A = col_integer(),
  Q16I = col_integer(),
  Q16E = col_integer(),
  Q17A = col_integer(),
  Q17I = col_integer(),
  Q17E = col_integer(),
  Q18A = col_integer(),
  Q18I = col_integer(),
  Q18E = col_integer(),
  Q19A = col_integer(),
  Q19I = col_integer(),
  Q19E = col_integer(),
  Q20A = col_integer(),
  Q20I = col_integer(),
  Q20E = col_integer(),
  country = col_character(),
  introelapse = col_integer(),
  testelapse = col_integer(),
  surveyelapse = col_integer(),
  TIPI1 = col_integer(),
  TIPI2 = col_integer(),
  TIPI3 = col_integer(),
  TIPI4 = col_integer(),
  TIPI5 = col_integer(),
  TIPI6 = col_integer(),
  TIPI7 = col_integer(),
  TIPI8 = col_integer(),
  TIPI9 = col_integer(),
  TIPI10 = col_integer(),
  VCL1 = col_integer(),
  VCL2 = col_integer(),
  VCL3 = col_integer(),
  VCL4 = col_integer(),
  VCL5 = col_integer(),
  VCL6 = col_integer(),
  VCL7 = col_integer(),
  VCL8 = col_integer(),
  VCL9 = col_integer(),
  VCL10 = col_integer(),
  VCL11 = col_integer(),
  VCL12 = col_integer(),
  VCL13 = col_integer(),
  VCL14 = col_integer(),
  VCL15 = col_integer(),
  VCL16 = col_integer(),
  education = col_integer(),
  urban = col_integer(),
  gender = col_integer(),
  engnat = col_integer(),
  age = col_integer(),
  screenw = col_integer(),
  screenh = col_integer(),
  hand = col_integer(),
  religion = col_integer(),
  orientation = col_integer(),
  race = col_integer(),
  voted = col_integer(),
  married = col_integer(),
  familysize = col_integer(),
  major = col_character()
)
mach <- read_tsv(path("data", "raw", "MACH_data", "data.csv"),
                 col_types = mach_spec,
                 na = c("", "NA", "NULL"))

#----write----
dir_create("data", "feather")
write_feather(mach, path("data", "feather", "mach.feather"))
